api_platform:
  defaults:
    pagination_items_per_page: 12
    pagination_maximum_items_per_page: 12
  swagger:
    api_keys:
      JWT:
        name: Authorization
        type: header

  oauth:
    # To enable or disable OAuth.
    enabled: true

    # The OAuth client ID.
    clientId: ''

    # The OAuth client secret.
    clientSecret: ''

    # The OAuth type.
    type: 'oauth2'

    # The OAuth flow grant type.
    flow: 'application'

    # The OAuth token URL. Make sure to check the specification tokenUrl is not needed for an implicit flow.
    tokenUrl: ''

    # The OAuth authentication URL.
    authorizationUrl: ''

    # The OAuth scopes.
    scopes: [ ]